### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by chxp82q** [OwO-Digital/nixos-config#1]
fix tab width pls thanks :pray:

**Comment by emifloofy** [comment]
i'll work on it, i hate it when editors replace tabs with spaces..

**Comment by chxp82q** [comment]
> i'll work on it, i hate it when editors replace tabs with spaces..

Thank god you use nixos now so u can declaratively tell ur editor to stop 👍

**Comment by emifloofy** [comment]
closed by 3952d8cfa4ba3a64f260ba19cc7b68b12b870940 :p

**Comment by emifloofy** [comment]
nevermind i'm stupid and eclint only worked on lua files and not nix files

**Comment by emifloofy** [comment]
nevermind 2, this seems to have worked lol b950cf09fed6ec1cad498d834438d77967526fc3
hopefully i didn't miss anything

gonna keep the issue open anyways tho, just in case

**Comment by emifloofy** [comment]
since [`Formatting Check`](https://github.com/OwO-Digital/nixos-config/blob/main/.github/workflows/format.yml) is now a gh action, i guess i can actually close this now kek
